/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ImgImageIdRouteImport } from './routes/img.$imageId'
import { Route as AdminPIdRouteImport } from './routes/admin/p.$id'
import { Route as AdminApiUploadRouteImport } from './routes/admin/api/upload'
import { Route as AdminApiSaveRouteImport } from './routes/admin/api/save'
import { Route as AdminApiCreatePageRouteImport } from './routes/admin/api/create-page'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ImgImageIdRoute = ImgImageIdRouteImport.update({
  id: '/img/$imageId',
  path: '/img/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPIdRoute = AdminPIdRouteImport.update({
  id: '/admin/p/$id',
  path: '/admin/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApiUploadRoute = AdminApiUploadRouteImport.update({
  id: '/admin/api/upload',
  path: '/admin/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApiSaveRoute = AdminApiSaveRouteImport.update({
  id: '/admin/api/save',
  path: '/admin/api/save',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApiCreatePageRoute = AdminApiCreatePageRouteImport.update({
  id: '/admin/api/create-page',
  path: '/admin/api/create-page',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/img/$imageId': typeof ImgImageIdRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/api/create-page': typeof AdminApiCreatePageRoute
  '/admin/api/save': typeof AdminApiSaveRoute
  '/admin/api/upload': typeof AdminApiUploadRoute
  '/admin/p/$id': typeof AdminPIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/img/$imageId': typeof ImgImageIdRoute
  '/p/$slug': typeof PSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/api/create-page': typeof AdminApiCreatePageRoute
  '/admin/api/save': typeof AdminApiSaveRoute
  '/admin/api/upload': typeof AdminApiUploadRoute
  '/admin/p/$id': typeof AdminPIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/img/$imageId': typeof ImgImageIdRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/api/create-page': typeof AdminApiCreatePageRoute
  '/admin/api/save': typeof AdminApiSaveRoute
  '/admin/api/upload': typeof AdminApiUploadRoute
  '/admin/p/$id': typeof AdminPIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/img/$imageId'
    | '/p/$slug'
    | '/admin/'
    | '/admin/api/create-page'
    | '/admin/api/save'
    | '/admin/api/upload'
    | '/admin/p/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/img/$imageId'
    | '/p/$slug'
    | '/admin'
    | '/admin/api/create-page'
    | '/admin/api/save'
    | '/admin/api/upload'
    | '/admin/p/$id'
  id:
    | '__root__'
    | '/'
    | '/img/$imageId'
    | '/p/$slug'
    | '/admin/'
    | '/admin/api/create-page'
    | '/admin/api/save'
    | '/admin/api/upload'
    | '/admin/p/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImgImageIdRoute: typeof ImgImageIdRoute
  PSlugRoute: typeof PSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminApiCreatePageRoute: typeof AdminApiCreatePageRoute
  AdminApiSaveRoute: typeof AdminApiSaveRoute
  AdminApiUploadRoute: typeof AdminApiUploadRoute
  AdminPIdRoute: typeof AdminPIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/img/$imageId': {
      id: '/img/$imageId'
      path: '/img/$imageId'
      fullPath: '/img/$imageId'
      preLoaderRoute: typeof ImgImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/p/$id': {
      id: '/admin/p/$id'
      path: '/admin/p/$id'
      fullPath: '/admin/p/$id'
      preLoaderRoute: typeof AdminPIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api/upload': {
      id: '/admin/api/upload'
      path: '/admin/api/upload'
      fullPath: '/admin/api/upload'
      preLoaderRoute: typeof AdminApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api/save': {
      id: '/admin/api/save'
      path: '/admin/api/save'
      fullPath: '/admin/api/save'
      preLoaderRoute: typeof AdminApiSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api/create-page': {
      id: '/admin/api/create-page'
      path: '/admin/api/create-page'
      fullPath: '/admin/api/create-page'
      preLoaderRoute: typeof AdminApiCreatePageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImgImageIdRoute: ImgImageIdRoute,
  PSlugRoute: PSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminApiCreatePageRoute: AdminApiCreatePageRoute,
  AdminApiSaveRoute: AdminApiSaveRoute,
  AdminApiUploadRoute: AdminApiUploadRoute,
  AdminPIdRoute: AdminPIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
